exec-once = awww-daemon

exec-once = swaync
exec-once = waybar

env = password-store,kwallet

# Start the KWallet daemon
exec-once = /usr/libexec/kf6/kwalletd6

# Bridge KWallet to the Freedesktop Secret Service API
# (This is what allows non-KDE apps like Chrome/VSCode to talk to KWallet)
exec-once = /usr/bin/kwallet-query -l kdewallet
